stages:
  - test
  - build
  - build-image

test:
  image: docker.oxygene.sk/acoustid/docker-compose
  variables:
    COMPOSE_PROJECT_NAME: gitlab_${CI_PROJECT_ID}_${CI_JOB_ID}
    COMPOSE_FILE: docker-compose.test.yml
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose up -d postgres-test
    - docker-compose run test
  after_script:
    - docker-compose down
  tags:
    - docker-host

build:
  stage: build
  image: golang:1.9
  script:
    - mkdir -p $GOPATH/src/github.com/acoustid
    - ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/acoustid/priv
    - go build github.com/acoustid/priv/cmd/acoustid-priv-api
  artifacts:
    paths:
      - acoustid-priv-api
    expire_in: 1w

build-image:
  stage: build-image
  image: docker
  script:
    - mv acoustid-priv-api docker/
    - tmp_tag=tmp-${CI_PROJECT_ID}-${CI_JOB_ID}
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$tmp_tag docker/
    - if [ -n "$CI_COMMIT_TAG" ]
    - then
    -   tag=$(echo $CI_COMMIT_TAG | sed 's/^v//')
    - else
    -   tag=$CI_COMMIT_REF_SLUG
    - fi
    - docker tag $CI_REGISTRY_IMAGE:$tmp_tag $CI_REGISTRY_IMAGE:$tag
    - docker push $CI_REGISTRY_IMAGE:$tag
    - if [ -n "$CI_COMMIT_TAG" ]
    -   docker tag $CI_REGISTRY_IMAGE:$tmp_tag $CI_REGISTRY_IMAGE:latest
    -   docker push $CI_REGISTRY_IMAGE:latest
    - fi