stages:
  - test
  - build
  - build-image

test:
  image: docker.oxygene.sk/acoustid/docker-compose
  variables:
    COMPOSE_PROJECT_NAME: gitlab_${CI_PROJECT_ID}_${CI_JOB_ID}
    COMPOSE_FILE: docker-compose.test.yml
  script:
    - cd $CI_PROJECT_DIR
    - docker-compose up -d postgres-test
    - docker-compose run test
  after_script:
    - docker-compose down
  tags:
    - docker-host

build:
  stage: build
  image: golang:1.9-alpine
  script:
    - mkdir -p $GOPATH/src/github.com/acoustid
    - ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/acoustid/priv
    - go build github.com/acoustid/priv/cmd/acoustid-priv-api
  artifacts:
    paths:
      - acoustid-priv-api
    expire_in: 1w

build-image:
  stage: build-image
  image: docker
  script:
    - mv acoustid-priv-api docker/
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG docker/
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
