FROM golang:1.9

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/bin/
ADD scripts/run-tests.sh /usr/bin/
RUN chmod a+rx /usr/bin/wait-for-it.sh /usr/bin/run-tests.sh

CMD ["/usr/bin/run-tests.sh"]
