version: "3"
services:

  postgres:
    image: postgres:alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/10-schema.sql
    environment:
      POSTGRES_USER: acoustid
      POSTGRES_DB: acoustid
