name: Build image

on:
  push: {}

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: acoustid
          POSTGRES_PASSWORD: notasecret
          POSTGRES_DB: acoustid_priv_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup database
        run: |
          container=$(docker ps -q -f expose=5432)
          docker exec -i -e PGUSER=$PGUSER -e PGPASSWORD=$PGPASSWORD -e PGDATABASE=$PGDATABASE $container psql  < ./sql/init_db.sql
          docker exec -i -e PGUSER=$PGUSER -e PGPASSWORD=$PGPASSWORD -e PGDATABASE=$PGDATABASE $container psql < ./sql/schema.sql
          docker exec -i -e PGUSER=$PGUSER -e PGPASSWORD=$PGPASSWORD -e PGDATABASE=$PGDATABASE $container psql < ./sql/fixtures.sql
        env:
          PGUSER: acoustid
          PGPASSWORD: notasecret
          PGDATABASE: acoustid_priv_test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - test
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Check version details
      id: info
      run: |
        echo ::set-output name=IMAGE::quay.io/acoustid/acoustid-priv
        if [[ $GITHUB_REF == refs/tags/v* ]]
        then
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3 | sed 's/^v//')
        else
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3)
        fi

    - name: Build image
      run: |
        docker build -t ${{ steps.info.outputs.IMAGE }}:${{ steps.info.outputs.VERSION }} .

    - name: Push image
      run: |
        echo ${{ secrets.QUAY_PASSWORD }} | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin
        docker push ${{ steps.info.outputs.IMAGE }}:${{ steps.info.outputs.VERSION }}
